### ISSUE TITLE
Url parameter issues in 1.7 release for Shiny apps

### ISSUE THREAD

**Issue by LanceJensen-General** [att/rcloud.shiny#12]
In the 1.6 release of R Cloud the session variable of a shiny app contained the url parameters and could be accessed as follows:

session$clientData$url_search

Now that objects values seem to always be empty.

**Comment by gordonwoodhull** [comment]
Thanks for the report @LanceJensen-General.

For future reference, it was easy for me to test with this notebook:
https://rcloud.social/shiny.html?notebook=1c99090f0a62d5ade3f6753f47a22de4

which is based on 
http://shiny.rstudio.com/articles/client-data.html

Indeed, we just needed to pass the search string (and hash, for completeness) down from the main document to the iframe. This will be fixed in 0.4.1.
